version: 2

models:
  - name: dim_customers
    description: Contains customers information such as name, phone or region.

  - name: dim_parts
    description: Contains parts information such as name, type, brand or size.

  - name: dim_suppliers
    description: Contains suppliers information such as name, phone or region.